version: '2'
services:
   karmasoc-api:
        image: "karmasocio/karmasoc-api"
        build:
            context: .
            dockerfile: Dockerfile.karmasocapi.k8
        restart: always
        hostname: karmasoc-api
        ports:
          - "8200:8200"
        environment:
            FILELOGLEVEL: error
