# karmasoc-api
FROM node:6.8.0

ARG WORKSPACE=/usr/src/app/karmasoc-api

# Create app directory
RUN mkdir -p $WORKSPACE
RUN mkdir -p $WORKSPACE/config
RUN mkdir -p $WORKSPACE/logs

COPY ./process.json $WORKSPACE
COPY ./config $WORKSPACE/config
COPY ./karmasoc-firebase-adminsdk.json $WORKSPACE/karmasoc-firebase-adminsdk.json

COPY . $WORKSPACE

WORKDIR $WORKSPACE

RUN npm install --unsafe-perm=true
RUN npm run prestart

EXPOSE 8200

CMD npm run watch